/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 17-Jun-2021 1:47:31 PM 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Cuadrangular" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Cuadrangular_Equipo" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Equipo" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Partido" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "Cuadrangular"
(
	"K_ID" VARCHAR2(10) NOT NULL,
	"N_NAME" VARCHAR2(50) NOT NULL
)
;

CREATE TABLE  "Cuadrangular_Equipo"
(
	"K_ID_CUAGRANGULAR" VARCHAR2(10) NOT NULL,
	"K_ID_EQUIPO" VARCHAR2(10) NOT NULL
)
;

CREATE TABLE  "Equipo"
(
	"K_ID" VARCHAR2(10) NOT NULL,
	"N_NAME" VARCHAR2(50) NOT NULL,
	"Q_PUNTOS" NUMBER(2) NULL
)
;

CREATE TABLE  "Partido"
(
	"K_EQUIPO1_ID" VARCHAR2(10) NOT NULL,
	"K_EQUIPO2_ID" VARCHAR2(10) NOT NULL,
	"Q_GOL_EQ1" NUMBER(2) NULL,
	"Q_GOL_EQ2" NUMBER(2) NULL,
	"O_OBSERVACION" VARCHAR2(50) NULL,
	"F_PARTIDO" DATE NULL,
	"Q_HORA" VARCHAR2(10) NULL,
	"N_LUGAR" VARCHAR2(20) NULL
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  "Cuadrangular_Equipo" IS 'Table de rompimiento entre la table Cuadrangular y la table Equpo.'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "Cuadrangular" 
 ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY ("K_ID") 
 USING INDEX
;

ALTER TABLE  "Cuadrangular_Equipo" 
 ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY ("K_ID_CUAGRANGULAR","K_ID_EQUIPO") 
 USING INDEX
;

ALTER TABLE  "Equipo" 
 ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY ("K_ID") 
 USING INDEX
;

ALTER TABLE  "Equipo" 
 ADD CONSTRAINT "CHK_PUNTOS" CHECK (Q_PUNTOS > -1 and Q_PUNTOS < 10)
;

ALTER TABLE  "Partido" 
 ADD CONSTRAINT "PK_Partido"
	PRIMARY KEY ("K_EQUIPO1_ID","K_EQUIPO2_ID") 
 USING INDEX
;

ALTER TABLE  "Partido" 
 ADD CONSTRAINT "CHK_GOL_EQ1" CHECK (Q_GOL_EQ1 > -1)
;

ALTER TABLE  "Partido" 
 ADD CONSTRAINT "CHK_GOL_EQ2" CHECK (Q_GOL_EQ2 > -1)
;

/* Create Foreign Key Constraints */

ALTER TABLE  "Cuadrangular_Equipo" 
 ADD CONSTRAINT "FK_Cuadrangular_Cuadrangula_01"
	FOREIGN KEY ("K_ID_CUAGRANGULAR") REFERENCES  "Cuadrangular" ("K_ID")
;

ALTER TABLE  "Cuadrangular_Equipo" 
 ADD CONSTRAINT "FK_Cuadrangular_Equipo_Equipo"
	FOREIGN KEY ("K_ID_EQUIPO") REFERENCES  "Equipo" ("K_ID")
;

ALTER TABLE  "Partido" 
 ADD CONSTRAINT "FK_Partido_Equipo"
	FOREIGN KEY ("K_EQUIPO1_ID") REFERENCES  "Equipo" ("K_ID")
;

ALTER TABLE  "Partido" 
 ADD CONSTRAINT "FK_Partido_Equipo02"
	FOREIGN KEY ("K_EQUIPO2_ID") REFERENCES  "Equipo" ("K_ID")
;
